#!/bin/bash
# Copyright 2019, Alex Wiens <awiens@mail.upb.de>, Achim Lösch <achim.loesch@upb.de>
# SPDX-License-Identifier: BSD-2-Clause


if [ $# -lt 1 ]; then
	echo "Not enough arguments."
	exit 1
fi

if [ $1 == "sim" ]; then
	echo "conf_execsuspend: can not be simulated"
	exit 1
fi

$SCHED_ENV/scripts/test.sh "$1"
